[project]
name = "groqbackend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "aiofiles>=23.2.1",
    "aiogram>=3.10.0",
    "alembic>=1.18.3",
    "asyncpg>=0.29.0",
    "fastapi>=0.110.0",
    "langchain-community>=0.3.21",
    "numpy<2.0",
    "openai>=1.40.0",
    "pre-commit>=4.5.1",
    "pydantic>=2.8.0",
    "pydantic-settings>=2.4.0",
    "python-multipart>=0.0.9",
    "qdrant-client>=1.12.1",
    "requests>=2.32.0",
    "scikit-learn>=1.5.0",
    "sentence-transformers>=3.0.0",
    "sqlalchemy>=2.0.30",
    "types-aiofiles>=25.1.0.20251011",
    "uvicorn>=0.30.0",
]
